#!/bin/bash -e

## Install Ansible and Git
apt-get update
app-get install -y git-core ansible

#Setup working directory
mkdir ~/pup
cd ~/pup

#Grab all the things
git clone https://github.com/sctpwolf/puppet-nginx-test ~/pup

#Provision Server
ansible-playbook playbook.yml
