---
- hosts: localhost
  sudo: true

  handlers:

   - name: reload nginx
     service: name=nginx state=reloaded

  tasks:

    - name: ensure webroot exists
      file: path=/var/www/pup state=directory

    - name: update apt cache
      apt: update_cache=yes

    - name: install git
      apt: name=git state=present

    - name: install nginx
      apt: name=nginx state=present

#    - name: insert/update "Match User" configuration block in /etc/ssh/sshd_config
#      blockinfile:
#        dest: /etc/nginx/sites-available/default
#        insertafter: {^server {/t}
#        block: |
#          listen 8000;
#          listen [::]:8000;
#        state: present
    - name: Ensure port is correct
      template: src=~/pup/nginxconf.j2 dest=/etc/ngnix/sites-available/default owner=root group=root mode=644
      notify:
        - reload nginx

    - name: ensure nginx is running
      service: name=nginx state=started

    - name: ensure current web content
      git:
        repo: https://github.com/puppetlabs/exercise-webpage
        dest: /var/www/pup
        update: yes
      notify:
        - reload nginx

#  - name: Copy across new nginx config
#    template:
#        src=~/puppetest/default
#        dest=/etc/nginx/sites-available/default
