---
- hosts: localhost
  sudo: true
  vars:
    port: 8000

  handlers:

   - name: reload nginx
     service: name=nginx state=reloaded

  tasks:

    - name: ensure webroot exists
      file: path=/var/www/pup state=directory

    - name: update apt cache
      apt: update_cache=yes

    - name: install git
      apt: name=git state=present

    - name: install nginx
      apt: name=nginx state=present
      
    - name: Ensure port is correct
      template:	src=~/pup/nginxconf.j2 dest=/etc/nginx/sites-available/default owner=root group=root mode=644 follow=yes
      notify:
        - reload nginx

    - name: ensure current web content
      git:
        repo: https://github.com/puppetlabs/exercise-webpage
        dest: /var/www/pup
        update: yes
      notify:
        - reload nginx
        
    - name: ensure nginx is running
      service: name=nginx state=started
      
